# 部署到 GitHub Pages 的简单工作流
name: Deploy to GitHub Pages

# 触发条件：当有代码推送到 main 分支时
on:
  push:
    branches: [ "main" ]

# 工作流权限
permissions:
  contents: read
  pages: write
  id-token: write

# 部署任务
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 获取你的代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建项目（这里我们不需要 base 配置）
      - name: Build
        run: npm run build
      
      # 5. 上传构建好的产物用于部署
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      # 6. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4